# Generated by Django 5.2.8 on 2025-11-07 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_operacion', models.CharField(choices=[('Renta', 'Renta'), ('Venta', 'Venta')], max_length=10)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Rentada', 'Rentada'), ('Vendida', 'Vendida')], default='Disponible', max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('num_habitaciones', models.PositiveIntegerField(default=1)),
                ('num_baños', models.PositiveIntegerField(default=1)),
                ('metros_cuadrados', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_renta_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_pago_mensual', models.PositiveIntegerField(default=1)),
                ('frecuencia_aumento_meses', models.PositiveIntegerField(default=12, help_text='¿Cada cuántos meses se aplica el aumento? (ej. 12)')),
                ('porcentaje_aumento', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje de aumento (ej. 10 para 10%)', max_digits=5)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propiedades.cliente')),
                ('propiedad', models.ForeignKey(limit_choices_to={'estado': 'Disponible', 'tipo_operacion': 'Renta'}, on_delete=django.db.models.deletion.PROTECT, to='propiedades.propiedad')),
            ],
        ),
    ]
