# Generated by Django 5.2.8 on 2025-11-08 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
        migrations.CreateModel(
            name='FotoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_galeria', to='propiedades.propiedad')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Fotos de Galería',
            },
        ),
    ]
