# Generated by Django 5.2.8 on 2025-11-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_cliente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Vencido', 'Vencido')], default='Pendiente', max_length=10)),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha en que se confirmó el pago', null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='propiedades.contrato')),
            ],
            options={
                'verbose_name': 'Pago Mensual',
                'verbose_name_plural': 'Pagos Mensuales',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
    ]
